version: "3.8"
services:
    flask:
        build: ./python
        container_name: rpg-tools-flask-app
        restart: always
        environment:
            - APP_NAME=rpg-tools-flask-app
        expose:
            - 8080
        # volumes:
        #     - ./python/log/uwsgi:/var/log/uwsgi

    nginx:
        build: ./nginx
        container_name: rpg-tools-nginx
        restart: always
        ports:
            - "80:80"
