[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "rpg_tools"
description = "A collection of character generators and tools for RPGs"
readme = "README.md"
authors = [{name = "Jeremy Deram"}]
urls = {homepage = "https://github.com/jderam/rpg_tools"}
license = {file = "LICENSE"}
keywords = [
    "Dungeons",
    "Dragons",
    "RPG",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dynamic = [
    "version",
]
requires-python = ">=3.11"
dependencies = []

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov",
    "pytest-repeat",
    "ruff",
]
dev = [
    "fastapi",
    "ipython",
    "mypy",
    "pre-commit",
    "uvicorn",
]
all = [
    "rpg_tools[test]",
    "rpg_tools[dev]",
]

[tool.hatch.version]
path = "rpg_tools/__init__.py"

[tool.hatch.build.targets.wheel]
packages = ["rpg_tools"]

[tool.pytest.ini_options]
addopts = "--cov=rpg_tools"
testpaths = ["tests"]
markers = [
    "repeat: repeats a test n times",
]

[tool.mypy]
mypy_path = "rpg_tools"
check_untyped_defs = true
disallow_any_generics = true
ignore_missing_imports = false
no_implicit_optional = true
show_error_codes = true
strict_equality = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
no_implicit_reexport = true

[tool.ruff]
line-length = 100
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "W"]

[tool.ruff.lint.per-file-ignores]
"rpg_tools/tiny_dungeon/data.py" = ["E501"]
"rpg_tools/misc_data/knave_spells.py" = ["E501"]
"rpg_tools/misc_data/dying_earth_spells.py" = ["E501"]
