abilities = [
    [2, 1, 0],
    [2, 0, 1],
    [1, 2, 0],
    [0, 2, 1],
    [1, 0, 2],
    [0, 1, 2],
]

abilities2 = {
    1: 0,
    2: 0,
    3: 1,
    4: 1,
    5: 1,
    6: 2,
}

gender = [
    "Male",
    "Female",
    "Non-Binary",
]

features = {
    1: "+1 Attack Bonus",
    2: "One Spell Slot",
    3: "Briarborn: Tracking, Foraging, Survival",
    4: "Fingersmith: Tinkering, Picking Locks, Picking Pockets",
    5: "Roofrunner: Climbing, Leaping, Balancing",
    6: "Shadowjack: Moving Silently, Hiding in Shadows",
}

items = [
    "Animal Scent",
    "Bear Trap",
    "Bedroll",
    "Caltrops",
    "Chain (10 ft)",
    "Chalk",
    "Chisel",
    "Crowbar",
    "Fishing Net",
    "Glass Marbles",
    "Glue",
    "Grappling Hook",
    "Grease",
    "Hacksaw",
    "Hammer",
    "Hand Drill",
    "Horn",
    "Iron Spikes",
    "Iron Tongs",
    "Lantern and Oil",
    "Large Sack",
    "Lockpicks (3)",
    "Manacles",
    "Medicine (3)",
    "Metal File",
    "Rations (3)",
    "Rope (50 ft)",
    "Steel Wire",
    "Shovel",
    "Steel Mirror",
    "Ten Foot Pole",
    "Tinderbox",
    "Torch",
    "Vial of Acid",
    "Vial of Poison",
    "Waterskin",
]

starting_gear = [
    "Light Armor (AC 7)",
]

light_weapons = [
    "[L] Axe",
    "[L] Dagger",
    "[L] Mace",
    "[L] Short Sword",
    "[L] Flail",
    "[L] One-Handed Spear",
]

heavy_weapons = [
    "[H] Spear",
    "[H] Halberd",
    "[H] Greatsword",
    "[H] Maul",
    "[H] Warhammer",
]

ranged_weapons = [
    "[R] Bow",
    "[R] Crossbow",
    "[R] Sling",
]

appearances = [
    "Aquiline",
    "Athletic",
    "Barrel-Chested",
    "Boney",
    "Brawny",
    "Brutish",
    "Bullnecked",
    "Chiseled",
    "Coltish",
    "Corpulent",
    "Craggy",
    "Delicate",
    "Furrowed",
    "Gaunt",
    "Gorgeous",
    "Grizzled",
    "Haggard",
    "Handsome",
    "Hideous",
    "Lanky",
    "Pudgy",
    "Ripped",
    "Rosy",
    "Scrawny",
    "Sinewy",
    "Slender",
    "Slumped",
    "Solid",
    "Square-Jawed",
    "Stauesque",
    "Towering",
    "Trim",
    "Weathered",
    "Willowy",
    "Wiry",
    "Wrinkled",
]

physical_details = [
    "Acid Scars",
    "Battle Scars",
    "Birthmark",
    "Braided Hair",
    "Brand Mark",
    "Broken Nose",
    "Bronze Skinned",
    "Burn Scars",
    "Bushy Eyebrows",
    "Curly Hair",
    "Dark Skinned",
    "Dreadlocks",
    "Exotic Accent",
    "Flogging Scars",
    "Freckles",
    "Gold Tooth",
    "Hoarse Voice",
    "Huge Beard",
    "Long Hair",
    "Matted Hair",
    "Missing Ear",
    "Missing Teeth",
    "Mustache",
    "Muttonchops",
    "Nine Fingers",
    "Oiled Hair",
    "One-Eyed",
    "Pale Skinned",
    "Piercings",
    "Ritual Scars",
    "Sallow Skin",
    "Shaved Head",
    "Sunburned",
    "Tangled Hair",
    "Tattoos",
    "Topknot",
]

backgrounds = [
    "Alchemist",
    "Beggar-Prince",
    "Blackmailer",
    "Bounty-Hunter",
    "Chimney Sweep",
    "Coin-Clipper",
    "Contortionist",
    "Counterfeiter",
    "Cultist",
    "Cutpurse",
    "Debt-Collector",
    "Deserter",
    "Fence",
    "Fortuneteller",
    "Galley Slave",
    "Gambler",
    "Gravedigger",
    "Headsman",
    "Hedge Knight",
    "Highwayman",
    "Housebreaker",
    "Kidnapper",
    "Mad Prophet",
    "Mountebank",
    "Peddler",
    "Pit Fighter",
    "Poisoner",
    "Rat-Catcher",
    "Scrivener",
    "Sellsword",
    "Slave",
    "Smuggler",
    "Street Performer",
    "Tattooist",
    "Urchin",
    "Usurer",
]

clothing = [
    "Antique",
    "Battle-Torn",
    "Bedraggled",
    "Blood-Stained",
    "Ceremonial",
    "Dated",
    "Decaying",
    "Eccentric",
    "Elegant",
    "Embroidered",
    "Exotic",
    "Fashionable",
    "Flamboyant",
    "Food-Stained",
    "Formal",
    "Frayed",
    "Frumpy",
    "Garish",
    "Grimy",
    "Haute Couture",
    "Lacey",
    "Livery",
    "Mud-Stained",
    "Ostentatious",
    "Oversized",
    "Patched",
    "Patterned",
    "Perfumed",
    "Practical",
    "Rumpled",
    "Sigils",
    "Singed",
    "Tasteless",
    "Undersized",
    "Wine-Stained",
    "Worn Out",
]

personalities = [
    "Bitter",
    "Brave",
    "Cautious",
    "Chipper",
    "Contrary",
    "Cowardly",
    "Cunning",
    "Driven",
    "Entitled",
    "Gregarious",
    "Grumpy",
    "Heartless",
    "Honor-Bound",
    "Hotheaded",
    "Inquisitive",
    "Irascible",
    "Jolly",
    "Know-It-All",
    "Lazy",
    "Loyal",
    "Menacing",
    "Mopey",
    "Nervous",
    "Protective",
    "Righteous",
    "Rude",
    "Sarcastic",
    "Savage",
    "Scheming",
    "Serene",
    "Spacey",
    "Stoic",
    "Stubborn",
    "Stuck-Up",
    "Suspicious",
    "Wisecracking",
]

mannerisms = [
    "Anecdotes",
    "Breathy",
    "Chuckles",
    "Clipped",
    "Cryptic",
    "Deep Voice",
    "Drawl",
    "Enunciates",
    "Flowery Speech",
    "Gravelly Voice",
    "Highly Formal",
    "Hypnotic",
    "Interrupts",
    "Laconic",
    "Laughs",
    "Long Pauses",
    "Melodious",
    "Monotone",
    "Mumbles",
    "Narrates",
    "Overly Casual",
    "Quaint Sayings",
    "Rambles",
    "Random Facts",
    "Rapid-Fire",
    "Rhyming",
    "Robotic",
    "Slow Speech",
    "Speechifies",
    "Squeaky",
    "Street Slang",
    "Stutters",
    "Talks to Self",
    "Trails Off",
    "Very Loud",
    "Whispers",
]
