# Dying Earth Spells for D&D
# Each spell: name, level, range, duration, aoe, save, description
# Spells with embedded tables include a "table" field:
#   {"headers": [...], "rows": [[...], ...]}
# Spells with multiple tables use "tables" (list of table dicts with optional "title")

dying_earth_spells = [
    {
        "name": "The Arcane Cypher",
        "level": 0,
        "range": "0",
        "duration": "2 rounds/level",
        "aoe": "Special",
        "save": "None",
        "description": "Read and understand magical inscriptions, scrolls, spell formulae, etc. Once deciphered can be read without recourse to spell.",
    },
    {
        "name": "The Abstention of the Written Path",
        "level": 1,
        "range": '6"',
        "duration": "1 turn",
        "aoe": '1"x1" area/round',
        "save": "None",
        "description": "Detect secret passages, portals and openings.",
    },
    {
        "name": "The Apotropaic Circle",
        "level": 1,
        "range": "Touch",
        "duration": "2 rounds/level",
        "aoe": '<1" diameter',
        "save": "None",
        "description": "Trace a circle in powdered silver; blocks all conjured & extraplanar creatures and possession attempts.",
    },
    {
        "name": "The Audible Glamer",
        "level": 1,
        "range": '6" + 1"/level',
        "duration": "2 rounds/level",
        "aoe": "Hearing range",
        "save": "None",
        "description": "Create auditory-only illusion.",
    },
    {
        "name": "The Call to the Familiar Spirit",
        "level": 1,
        "range": "Special",
        "duration": "Special",
        "aoe": "Special",
        "save": "None",
        "description": "Burn 1000 sp incense, herbs & fat, incantation lasting 24 hours. Summons familiar.",
    },
    {
        "name": "The Call to the Unseen Servant",
        "level": 1,
        "range": "0",
        "duration": "6 turns + 1/level",
        "aoe": "Special",
        "save": "None",
        "description": 'Invisible creature acts as valet, servant etc. AC 4, MV 18", HD 2; bound to obey caster but will not fight on their behalf. If abused seeks to pervert instructions.',
    },
    {
        "name": "The Charm of Appersonation",
        "level": 1,
        "range": "0",
        "duration": "2-12 rounds +2/lvl",
        "aoe": "Caster",
        "save": "None",
        "description": "Alter appearance and clothing to any humanoid figure. Cannot mimic specific individuals.",
    },
    {
        "name": "The Discerner of Enchantments",
        "level": 1,
        "range": '6"',
        "duration": "2 rounds/level",
        "aoe": '1" path',
        "save": "None",
        "description": "Detect magic and intensity.",
    },
    {
        "name": "The Effervescent Lights of Kwalish",
        "level": 1,
        "range": '4" + 1"/level',
        "duration": "1 turn/level",
        "aoe": "Special",
        "save": "None",
        "description": "Create A) 1-4 lights resembling torches, B) glowing spheres (as will-o-wisp), C) faintly glowing man-like shape. Moves as directed.",
    },
    {
        "name": "Evard's Frictionless Field",
        "level": 1,
        "range": '1"',
        "duration": "3 rounds + 1/level",
        "aoe": '1" square',
        "save": "Special",
        "description": "Save vs. spell or slip and fall. If cast on item then save or drop immediately.",
    },
    {
        "name": "The Expeditious Retreat",
        "level": 1,
        "range": "0",
        "duration": "3 rounds + 1/level",
        "aoe": "Caster",
        "save": "None",
        "description": "Triple movement, running jumps 30' forward or 10' up, cannot take any other action while moving.",
    },
    {
        "name": "The Heavenly Screen",
        "level": 1,
        "range": '3"',
        "duration": "2-8 rounds + 1/lvl",
        "aoe": '2"x2"x2" cube/level',
        "save": "None",
        "description": "Veil of silvery mist obscures vision beyond 2'.",
    },
    {
        "name": "The Howling Rune",
        "level": 1,
        "range": '1"',
        "duration": "4 hours + 1/level",
        "aoe": "1 object/creature",
        "save": "Negates",
        "description": "Target erupts in involuntary screaming (see Shrieker) when creature approaches within 10'.",
    },
    {
        "name": "The Hypnotic Charm",
        "level": 1,
        "range": '12"',
        "duration": "Special",
        "aoe": "1 person",
        "save": "Negates",
        "description": "Target regards caster as trusted friend and ally.",
        "table": {
            "headers": ["Intelligence", "Period Between Saving Throws"],
            "rows": [
                ["3 or less", "3 months"],
                ["4 to 6", "2 months"],
                ["7 to 9", "1 month"],
                ["10 to 12", "3 weeks"],
                ["13 to 14", "2 weeks"],
                ["15 to 16", "1 week"],
                ["17", "3 days"],
                ["18", "2 days"],
                ["19 or more", "1 day"],
            ],
        },
    },
    {
        "name": "The Imperturbable Quiescent Sphere",
        "level": 1,
        "range": "0",
        "duration": "5 rounds/level",
        "aoe": "Caster",
        "save": "None",
        "description": "Invisible barrier gives AC 2 vs. missiles, AC 4 vs. other attacks.",
    },
    {
        "name": "The Importunate Insult",
        "level": 1,
        "range": '3"',
        "duration": "Instantaneous",
        "aoe": "2 HD/caster level",
        "save": "Negates",
        "description": "Target rushes to attack magic-user in rage, attacking melee only.",
    },
    {
        "name": "The Indelible Emblem",
        "level": 1,
        "range": "Touch",
        "duration": "Permanent",
        "aoe": "<1 square foot",
        "save": "None",
        "description": "Inscribes personal mark and 6 other characters, visible or invisible.",
    },
    {
        "name": "Isain's Fortuitous Interruption",
        "level": 1,
        "range": '1"/level',
        "duration": "1 second/level",
        "aoe": "Special",
        "save": "None",
        "description": "200 lb + 200 per caster level assumes mass of a feather, no falling damage.",
    },
    {
        "name": "The Kaleidoscopic Spray",
        "level": 1,
        "range": "0",
        "duration": "Instantaneous",
        "aoe": '1/2"x2"x2" wedge',
        "save": "Special",
        "description": "Vivid colour spray affects 1d6 creatures. Caster level or below: unconscious 2-8 rounds. 1-2 levels higher: blind 1-4 rounds. 3 or more levels higher: stunned for 1 round. 6 HD or more gets a saving throw.",
    },
    {
        "name": "Kazimir's Resplendent Couture",
        "level": 1,
        "range": "0",
        "duration": "1 hour/level",
        "aoe": "Caster",
        "save": "None",
        "description": "Dazzlingly fashionable apparel, gain 2-8 charisma and viewers make immediate reaction checks, become impressed or jealous/irritated.",
    },
    {
        "name": "Laeral's Baleful Aura",
        "level": 1,
        "range": '3"',
        "duration": "1 round",
        "aoe": "Caster",
        "save": "Negates",
        "description": "Become unquantifiably terrifying; friends & foes save vs. magic or flee 1-3 rounds.",
    },
    {
        "name": "The Lesser Sign of Sealing",
        "level": 1,
        "range": '2"/level',
        "duration": "Permanent",
        "aoe": "80 square feet/lvl",
        "save": "None",
        "description": "Seal door or gate as if securely barred and locked.",
    },
    {
        "name": "Melf's Impermeable Membrane",
        "level": 1,
        "range": "Touch",
        "duration": "24 hours",
        "aoe": "<10 cubic feet/lvl",
        "save": "None",
        "description": "Repel all liquid from subject.",
    },
    {
        "name": "The Metamorphoun of Fire",
        "level": 1,
        "range": '1/2"/level',
        "duration": "2 rounds/level",
        "aoe": "10' radius",
        "save": "None",
        "description": "Increase fires up to double size/heat or down to embers, spread onto any burnable material, or snuff out all fires entirely.",
    },
    {
        "name": "Nahal's Reckless Dweomer",
        "level": 1,
        "range": "Special",
        "duration": "Special",
        "aoe": "Special",
        "save": "Special",
        "description": "Attempt to cast any spell in spellbook; roll results on Wild Surge table.",
    },
    {
        "name": "Otto's Arachnid Grip",
        "level": 1,
        "range": "Touch",
        "duration": "3 rounds +1/level",
        "aoe": "1 creature",
        "save": "Negates",
        "description": 'Climb vertical surfaces/ceilings at 3". Objects less than 5 lb stick to hands.',
    },
    {
        "name": "Phandaal's Polyglottal Lobe",
        "level": 1,
        "range": "Touch",
        "duration": "5 rounds/level",
        "aoe": "1 object/creature",
        "save": "None",
        "description": "Understand and speak any one language.",
    },
    {
        "name": "Sirrian's Aggrandisement",
        "level": 1,
        "range": '1/2"/level',
        "duration": "1 turn/level",
        "aoe": "<10 cubic feet/lvl",
        "save": "Negates",
        "description": "Increase or decrease target's size up to 200%, Strength & damage change proportionately.",
    },
    {
        "name": "The Spell of Exquisite Repose",
        "level": 1,
        "range": '3" + 1"/level',
        "duration": "5 rounds/level",
        "aoe": '3" diameter',
        "save": "None",
        "description": "Cause comatose slumber, awaken only if slapped/wounded.",
        "table": {
            "headers": ["Hit Dice", "Number Affected"],
            "rows": [
                ["Up to 1", "4-16 (4d4)"],
                ["1+1 to 2", "2-8 (2d4)"],
                ["2+1 to 3", "1-4 (1d4)"],
                ["3+1 to 4", "1-2 (1/2d4, round off)"],
                ["4+1 to 5", "0-1 (1d4, 3 or 4)"],
            ],
        },
    },
    {
        "name": "The Spell of Pragmatic Amalgamation",
        "level": 1,
        "range": '3"',
        "duration": "Permanent",
        "aoe": "5'x5' / level",
        "save": "None",
        "description": "Mend or rejoin broken objects.",
    },
    {
        "name": "Tenser's Floating Disc",
        "level": 1,
        "range": '2"',
        "duration": "3 turns + 1/level",
        "aoe": "Special",
        "save": "None",
        "description": "Floating null-gravity plane supports 100 lb per level, moves as directed.",
    },
    {
        "name": "Arbane's Fulgent Coruscations",
        "level": 2,
        "range": '12"',
        "duration": "Instantaneous",
        "aoe": "Special",
        "save": "None",
        "description": "Existing fire erupts in A) flashing fireworks, blind creatures within 12\" for 2-5 rounds or save vs. spell; or B) smoke 100 times volume of fire, obscure vision beyond 2', lasts 1 round/level.",
    },
    {
        "name": "The Call to the Foetid Cloud",
        "level": 2,
        "range": '3"',
        "duration": "1 round/level",
        "aoe": '2"x2"x2" cloud',
        "save": "Special",
        "description": "Billowing vapours, save vs. poison or incapacitated (nausea) for 2-5 rounds after leaving cloud, or 1 round if saved.",
    },
    {
        "name": "The Cure for Honesty",
        "level": 2,
        "range": '3"',
        "duration": "Permanent",
        "aoe": '2"x2"',
        "save": "Negates",
        "description": "1 to 4 creatures permanently forget previous 1 minute per level of spellcaster. -2 to save if single target.",
    },
    {
        "name": "The Hands of Cold Certainty",
        "level": 2,
        "range": '3"',
        "duration": "1 round/level",
        "aoe": "1 creature",
        "save": "Negates",
        "description": "Invisible hands choke target for 1-4 damage/round and -2 penalty to attack rolls.",
    },
    {
        "name": "Hornung's Deleterious Deflector",
        "level": 2,
        "range": "0",
        "duration": "2 rounds/level",
        "aoe": "Caster",
        "save": "None",
        "description": "Missile attacks deflected to random target in 15' radius (including caster).",
    },
    {
        "name": "The Impudent Might of Ilskar the Bold",
        "level": 2,
        "range": "Touch",
        "duration": "1 hour/level",
        "aoe": "1 creature",
        "save": "None",
        "description": "Raise Strength score 1-8 points.",
    },
    {
        "name": "The Invigorator of Blades",
        "level": 2,
        "range": "Touch",
        "duration": "1 turn",
        "aoe": "1 weapon",
        "save": "None",
        "description": "Blade receives +3 to hit and damage for 1 strike only.",
    },
    {
        "name": "Krest's Cerebral Consonance",
        "level": 2,
        "range": '1/2"/level',
        "duration": "1 round/level",
        "aoe": "1 creature/round",
        "save": "None",
        "description": "Read surface thoughts of 1 creature per round.",
    },
    {
        "name": "Leomund's Escalatory Escape",
        "level": 2,
        "range": "Touch",
        "duration": "2 turns/level",
        "aoe": "Special",
        "save": "None",
        "description": "Up to 6 creatures climb rope to hide in extradimensional space.",
    },
    {
        "name": "Lugwiler's Dismal Itch",
        "level": 2,
        "range": '1"/level',
        "duration": "1 round/level",
        "aoe": "1 creature",
        "save": "Negates",
        "description": "Horrible itching causes -4 to AC and -2 to attack rolls.",
    },
    {
        "name": "Lustoff's Vicarious Head",
        "level": 2,
        "range": '9" (initial)',
        "duration": "1 turn/level",
        "aoe": "1 creature",
        "save": "Negates",
        "description": "See through the senses of target creature.",
    },
    {
        "name": "The Manifold Effigies of Being",
        "level": 2,
        "range": "0",
        "duration": "3 rounds/level",
        "aoe": "Caster",
        "save": "None",
        "description": "D4 duplicates +1 per level form around caster, indistinguishable, disappear when struck.",
    },
    {
        "name": "The Marvellous Magic Mouth",
        "level": 2,
        "range": "Special",
        "duration": "Special",
        "aoe": "1 object",
        "save": "None",
        "description": "Magic mouth speaks message when specific condition is met.",
    },
    {
        "name": "Mazirian's Marasmic Malady",
        "level": 2,
        "range": '1" + 1/4"/level',
        "duration": "1 round/level",
        "aoe": "1 creature",
        "save": "Negates",
        "description": "Target reduced to Strength 3 or 50% damage.",
    },
    {
        "name": "The Pattern of the Immanent Sublime",
        "level": 2,
        "range": '3"',
        "duration": "Special",
        "aoe": '3"x3"',
        "save": "Negates",
        "description": "Display causes creatures to stand fascinated for as long as caster concentrates plus 2 rounds thereafter.",
    },
    {
        "name": "Phandaal's Mantle of Stealth",
        "level": 2,
        "range": "Touch",
        "duration": "2 rounds + 1/level",
        "aoe": "1 creature",
        "save": "None",
        "description": "Become invisible. Telltale shimmering allows attacks at -4 against invisible targets once spotted.",
    },
    {
        "name": "The Prosaic Preservation of Pandelume",
        "level": 2,
        "range": "Touch",
        "duration": "Permanent",
        "aoe": "10 cubic feet/level",
        "save": "None",
        "description": "Target protected from rot and decay. Reverse ages non-living objects 100 years.",
    },
    {
        "name": "Quaal's Near-Alchemical Transformance",
        "level": 2,
        "range": '1"',
        "duration": "1 hour/level",
        "aoe": "10 lb/level",
        "save": "None",
        "description": "Change lead to silver or copper to gold.",
    },
    {
        "name": "The Ruby Ray of Reversal",
        "level": 2,
        "range": '8"',
        "duration": "1 round",
        "aoe": "1 creature",
        "save": "Negates",
        "description": "Target repeats actions in last round exactly.",
    },
    {
        "name": "The Spell of Barring and Broaching",
        "level": 2,
        "range": '6"',
        "duration": "Permanent",
        "aoe": "10 square feet/lvl",
        "save": "None",
        "description": "A) Broaching: opens all doors, locks, bars, chains etc. B) Barring: closes the same.",
    },
    {
        "name": "The Spell of Phantasmal Forces",
        "level": 2,
        "range": '6" + 1"/level',
        "duration": "Special",
        "aoe": '4" + 1" sq/level',
        "save": "Special",
        "description": "Visual-only illusion lasts as long as caster concentrates.",
    },
    {
        "name": "The Spell of the Imponderous Bounty",
        "level": 2,
        "range": "Touch",
        "duration": "6 hours + 1/level",
        "aoe": "Caster",
        "save": "None",
        "description": "Enchant pockets to hold <100 lb or 5 cubic feet at 1/10th actual weight.",
    },
    {
        "name": "The Spur to the Libidinous Earth",
        "level": 2,
        "range": '10" + 1"/level',
        "duration": "3 rounds + 1/level",
        "aoe": "1 creature",
        "save": "Special",
        "description": "Earth hands hold target motionless by legs, -2 to AC. Save vs. spell each round in contact with ground or be gripped. Hands are AC 5, HP double caster's.",
    },
    {
        "name": "Tasha's Uncontrollable Hideous Laughter",
        "level": 2,
        "range": '5"',
        "duration": "4 rounds",
        "aoe": "1 creature",
        "save": "Negates",
        "description": "Lose actions for 1-4 rounds due to laughter.",
    },
    {
        "name": "The Tone of Resonant Discord",
        "level": 2,
        "range": '6"',
        "duration": "Instantaneous",
        "aoe": "3 foot radius",
        "save": "None",
        "description": "Crystalline or ceramic objects within 3' shatter.",
    },
    {
        "name": "The Torment of Tantalus",
        "level": 2,
        "range": '1"/level',
        "duration": "1 round/level",
        "aoe": "1 creature",
        "save": "Negates",
        "description": "Target dying of thirst, can do nothing but look for drink, consumes any potable liquids.",
    },
    {
        "name": "Turjan's Translocation",
        "level": 2,
        "range": '2"/level',
        "duration": "1 turn/level",
        "aoe": "1 object/creature",
        "save": "Negates",
        "description": "Levitate up to 100 lb vertically only, 20' per round.",
    },
    {
        "name": "The Unfettered Eye",
        "level": 2,
        "range": '1"/level',
        "duration": "1 round/level",
        "aoe": '1" path',
        "save": "None",
        "description": "Clearly see all invisible, astral, ethereal, hidden, out-of-phase creatures. First time casters save vs. magic or go insane 3-18 days due to terrifying abyssopelagic ethereal life.",
    },
    {
        "name": "The Veil of the Cimmerian Shade",
        "level": 2,
        "range": '1"/level',
        "duration": "1 turn + 1 rd/lvl",
        "aoe": '1 1/2" globe',
        "save": "None",
        "description": "Impenetrable darkness in area of effect.",
    },
    {
        "name": "The Web of Wondrous Entrapment",
        "level": 2,
        "range": '1/2"/level',
        "duration": "2 turns/level",
        "aoe": '3" cube',
        "save": "Neg or 1/2",
        "description": "Mass of webs, entrapped creatures are stuck, 5% cumulative chance per turn suffocate to death. Highly flammable. Strength 13+ break through 1'/round, huge strong creatures 10'/round.",
    },
    {
        "name": "Arbane's Precipitous Deluge",
        "level": 3,
        "range": '1"/level',
        "duration": "1 round/level",
        "aoe": '3" diameter',
        "save": "None",
        "description": "Instant rainfall drenches everything, extinguishes all fires including spells. Magical fires cause huge steam clouds for 1-3 damage/round lasting 2-5 rounds.",
    },
    {
        "name": "The Charm of Dire Sanguinity",
        "level": 3,
        "range": '12"',
        "duration": "1d4 rounds + 1/lvl",
        "aoe": "1 person",
        "save": "Negates",
        "description": "Target truly enjoys killing and goes berserk, attacking friend and foe alike.",
    },
    {
        "name": "The Charm of the Inveigling Tongue",
        "level": 3,
        "range": '3"',
        "duration": "1 hour + 1/level",
        "aoe": "1 creature",
        "save": "Negates",
        "description": 'Target obeys any one "reasonable" suggestion by caster.',
    },
    {
        "name": "Chun's Halo of the Unsleeping Eyes",
        "level": 3,
        "range": "0",
        "duration": "1 turn/level",
        "aoe": "Caster",
        "save": "None",
        "description": 'Halo of eyeballs let caster see in all directions, infravision 12", never surprised or backstabbed.',
    },
    {
        "name": "Felojun's Repudiation of Arrows",
        "level": 3,
        "range": "Touch",
        "duration": "1 turn/level",
        "aoe": "1 creature",
        "save": "None",
        "description": "Total invulnerability to small projectiles - arrows, axes, javelins etc - and -1 damage per die from large missiles, catapult stones etc.",
    },
    {
        "name": "The Fury of the Captive Wind",
        "level": 3,
        "range": "0",
        "duration": "1 round",
        "aoe": '1" path, 10"/level',
        "save": "None",
        "description": "Gust of air extinguishes unprotected flames, fans fires outward, pushes flying creatures backward, deflects missile fire and breath weapons, knocks man-sized creatures over unless roll under Dexterity.",
    },
    {
        "name": "The Globe of Distant Discernment",
        "level": 3,
        "range": "Special",
        "duration": "1 round/level",
        "aoe": "Special",
        "save": "None",
        "description": "See anything in sight from chosen locale; locale must be familiar or obvious.",
    },
    {
        "name": "The Indefatigable Breath",
        "level": 3,
        "range": "Touch",
        "duration": "1 hour/level + 1d4",
        "aoe": "Special",
        "save": "None",
        "description": "Function without breathing. Duration divided by number affected.",
    },
    {
        "name": "The Instant Galvanic Thrust",
        "level": 3,
        "range": '4" + 1"/level',
        "duration": "Instantaneous",
        "aoe": '1"x4" or 1/2"x8"',
        "save": "1/2",
        "description": "Lightning bolt causes d6 damage per level (or save for half). Ignites combustibles, sunders doors, splinters 1' stone, melts soft metal. Bolt reflects off non-conducting materials.",
    },
    {
        "name": "The Interminable Interim",
        "level": 3,
        "range": '1"/level',
        "duration": "Special",
        "aoe": "1 creature",
        "save": "Negates",
        "description": "Target encased in amber, suspended animation completely unaffected by anything until touched by caster. Direct spell or magic trap glyph.",
    },
    {
        "name": "The Invocation of the Open Sky",
        "level": 3,
        "range": "0",
        "duration": "1 turn/level + 1d6",
        "aoe": "Caster",
        "save": "None",
        "description": 'Caster can fly 24" (x1/2 ascending, x2 diving). Exact duration unknown/random.',
    },
    {
        "name": "Kuroth's Empathic Rapport",
        "level": 3,
        "range": '20" (initial)',
        "duration": "2 turns/level",
        "aoe": "1 creature/3 levels",
        "save": "None",
        "description": "Telepathic bond between willing subjects while on same plane of existence.",
    },
    {
        "name": "Leomund's Expansible Egg",
        "level": 3,
        "range": "Touch",
        "duration": "4 hours + 1/level",
        "aoe": '1" diameter',
        "save": "None",
        "description": "Hemisphere of force maintains comfortable temperature, keeps out wind/rain, transparent inside but opaque from without. Illuminated at caster's command. Objects/creatures pass through freely.",
    },
    {
        "name": "Leuk-O's Vile Menagerie",
        "level": 3,
        "range": '3"',
        "duration": "3 rounds + 1/level",
        "aoe": "Special",
        "save": "None",
        "description": "Give form to one or more monsters which are 90% likely to obey caster's commands. Roll below:",
        "tables": [
            {
                "title": "Size",
                "headers": ["Roll", "HD", "Number"],
                "rows": [
                    ["1", "4 HD", "1"],
                    ["2", "3 HD", "1d4"],
                    ["3-4", "2 HD", "1d6"],
                    ["5-6", "1 HD", "2d4"],
                ],
            },
            {
                "title": "Locomotion",
                "headers": ["Roll", "Locomotion", "Move"],
                "rows": [
                    ["1", "Slithering", '6"'],
                    ["2", "Hopping", '6" + 6"'],
                    ["3", "Skittering", '9"'],
                    ["4", "Loping", '12"'],
                    ["5", "Buzzing", '15"'],
                    ["6", "Flapping", '18"'],
                ],
            },
            {
                "title": "Type",
                "headers": ["Roll", "Type", "AC"],
                "rows": [
                    ["1", "Amoeboid", "AC 2"],
                    ["2", "Crustacean", "AC 3"],
                    ["3", "Insectoid", "AC 4"],
                    ["4", "Reptilian", "AC 5"],
                    ["5", "Amphibian", "AC 6"],
                    ["6", "Mammalian", "AC 7"],
                    ["7", "Avian", "AC 8"],
                    ["8", "Mollusc", "AC 9"],
                ],
            },
            {
                "title": "Attack",
                "headers": ["Roll", "Attack", "Damage"],
                "rows": [
                    ["1", "Stinging tail", "1d4"],
                    ["2", "Lashing tendrils", "1d4"],
                    ["3", "Crushers/horns", "1d6"],
                    ["4", "Rending claws", "1d6"],
                    ["5", "Slicing mandibles", "1d8"],
                    ["6", "Razor teeth", "1d8"],
                    ["7-8", "Roll twice", ""],
                ],
            },
            {
                "title": "Special",
                "headers": ["Roll", "Special", "Effect"],
                "rows": [
                    ["1", "Acid blood", "D4 damage after wounding"],
                    ["2", "Acid spit", "D6 damage ranged attack"],
                    ["3", "Big", "1/2 movement, x2 HD"],
                    ["4", "Bloodsucking", "Drain D6 damage/round after hit"],
                    ["5", "Draining", "-1 ST per hit"],
                    ["6", "Fast", "1/2 HD, x2 movement, x2 attack"],
                    ["7", "Invisible", "-4 to hit"],
                    ["8", "Ooze", "Dissolves metal"],
                    ["9", "Phase", "Move through walls"],
                    ["10", "Poison", "Save +4 or die"],
                    ["11", "Psychic", "Save vs. paralysis or stunned"],
                    ["12", "Prehensile tongue", "Extra attack as giant frog"],
                    ["13", "Regenerate", "1 hp/round"],
                    ["14", "Severing/mangling", "Natural 20 incapacitates limb"],
                    ["15", "Stinking", "-2 to hit within 10'"],
                    ["16-20", "Roll twice", ""],
                ],
            },
        ],
    },
    {
        "name": "The Liberation of Warp",
        "level": 3,
        "range": '12"',
        "duration": "Permanent",
        "aoe": '3" cube',
        "save": "None",
        "description": "Remove all temporary spells and disrupt spellcasting. % success equal to ratio of dispeller over spellcaster (e.g. 50% for 5th level vs. 10th level).",
    },
    {
        "name": "Lorloveim's Creeping Shadow",
        "level": 3,
        "range": "0",
        "duration": "1 round/level",
        "aoe": "Caster",
        "save": "None",
        "description": 'Elongate shadow at 15"/round. Can see, hear, speak through shadow. Struck only by magic, AC as caster, HP loss suffered by caster.',
    },
    {
        "name": "Melf's Maladweomer",
        "level": 3,
        "range": '4" + 1"/level',
        "duration": "Special",
        "aoe": "1 creature",
        "save": "Negates",
        "description": "Next spell cast chosen randomly from all spells in mind.",
    },
    {
        "name": "Mentzer's Relative Time Dilation",
        "level": 3,
        "range": '9" + 1"/level',
        "duration": "3 rounds + 1/level",
        "aoe": "1 creature/level",
        "save": "None",
        "description": "Affected creatures move and attack at 1/2 rate.",
    },
    {
        "name": "Mzhentul's Remarkable Polar Pull",
        "level": 3,
        "range": '3" + 1"/level',
        "duration": "1 round/2 levels",
        "aoe": "10' cube",
        "save": "None",
        "description": "Earth or stone object functions as magnet.",
        "table": {
            "headers": ["Distance from magnet", "Strength of attraction", "Missile attack penalty"],
            "rows": [
                ["<5'", "20", "-20"],
                ["<10'", "18", "-10"],
                ["<20'", "14", "-5"],
                ["<30'", "10", "-2"],
                ["<40'", "4", "-1"],
            ],
            "additional_text": "Opposed Strength check or ferrous item wrenched from grasp, armoured characters dragged closer distance in feet equal to number by which they failed.",
        },
    },
    {
        "name": "Nchaser's Spectral Steed",
        "level": 3,
        "range": "Touch",
        "duration": "1 hour/level",
        "aoe": "Special",
        "save": "None",
        "description": 'Phantasmal, milky-eyed horse-like creature will bear subject at movement 4" per caster level. Shunned by animals, crosses any terrain without difficulty. AC 2, HP 7 + caster level.',
    },
    {
        "name": "Nolzur's Metabolic Suspension",
        "level": 3,
        "range": "Touch",
        "duration": "6 hours + 1/level",
        "aoe": "1 creature",
        "save": "Negates",
        "description": "Target enters catalepsy indistinguishable from death; aware but unfeeling, wounds 1/2 damage, poison/paralysis/energy drain ineffective. 1 full round to restore bodily functions.",
    },
    {
        "name": "Nulathoe's Accoustic Enhancement",
        "level": 3,
        "range": "Special",
        "duration": "1 round/level",
        "aoe": "Special",
        "save": "None",
        "description": "Hear anything in range from chosen locale; locale must be familiar or obvious.",
    },
    {
        "name": "Phandaal's Vitriolic Critique",
        "level": 3,
        "range": "Touch",
        "duration": "Special",
        "aoe": '1" radius',
        "save": "1/2",
        "description": "Anyone besides caster (or those he/she instructs) reading text causes explosion, 6d4+6 damage with no save to reader, ditto all within blast radius or save for half. Writing is destroyed.",
    },
    {
        "name": "Rary's Erratic Displacement",
        "level": 3,
        "range": "0",
        "duration": "1 round/level",
        "aoe": "Caster",
        "save": "None",
        "description": "Teleport in random period (2d4 initiative order) and direction (d12 o'clock), 2' distance. 75% spell-casting fails while blinking. Opponents can attack only if initiative comes before the \"blink\".",
    },
    {
        "name": "The Seventh Set's Web of Hiding",
        "level": 3,
        "range": "Touch",
        "duration": "1 hour/level",
        "aoe": '1" radius',
        "save": "None",
        "description": "Immobile circle renders all creatures invisible & inaudible from those outside area of effect.",
    },
    {
        "name": "The Snapping Teeth of Yecind",
        "level": 3,
        "range": "Touch",
        "duration": "1 turn/level",
        "aoe": "1 creature/object",
        "save": "None",
        "description": "Snapping teeth in location touched attack creatures within 1', 1-4 damage as 4 HD monster.",
    },
    {
        "name": "The Solvent of Horrid Corrosion",
        "level": 3,
        "range": '1"',
        "duration": "3 rounds",
        "aoe": "1 sq foot/level",
        "save": "1/2",
        "description": "Acidic slime dissolves 6 inches wood, 4 inches stone, 1 inch metal per round. Flesh takes 2d4 damage per round.",
    },
    {
        "name": "The Spell of the Abysmal Flame",
        "level": 3,
        "range": '10" + 1"/level',
        "duration": "Instantaneous",
        "aoe": '2" radius sphere',
        "save": "1/2",
        "description": "Burst of flame causes d6 damage per level (or save for half), incinerates combustibles, melts soft metal. Flame conforms to shape of area, equal to normal spherical volume (33,000 cubic feet).",
    },
    {
        "name": "The Spell of the Slow Hour",
        "level": 3,
        "range": '6"',
        "duration": "3 rounds + 1/level",
        "aoe": "1 creature/level",
        "save": "None",
        "description": "Affected creatures function at 2x normal movement & attack. Reaction times, spell casting not affected. Recipients aged 1 year due to sped-up metabolism.",
    },
    {
        "name": "Xult's Peregrination of Probability",
        "level": 3,
        "range": "Special",
        "duration": "Instantaneous",
        "aoe": "Special",
        "save": "None",
        "description": "1 event taking place in previous round is recalculated (dice rerolled). Second outcome cannot be changed.",
    },
    {
        "name": "Alamer's Cloak of the Consuming Chill",
        "level": 4,
        "range": "0",
        "duration": "2 rounds + 1/level",
        "aoe": "Caster",
        "save": "None",
        "description": "Caster surrounded by aura of flame. A) cold flame, caster immune to fire, creatures striking in melee take 2-8 cold damage. Caster takes double damage from cold. B) hot flame, effects reversed.",
    },
    {
        "name": "Arnd's Dimension Door",
        "level": 4,
        "range": "Special",
        "duration": "Instant",
        "aoe": "Caster",
        "save": "None",
        "description": "Step through interspatial door and reappear anywhere in sight.",
    },
    {
        "name": "The Charm of the Inverted Pervulsion",
        "level": 4,
        "range": '3"',
        "duration": "Special",
        "aoe": "1 creature",
        "save": "Negates",
        "description": "Recipient's next offensive spell affects its own caster rather than intended target.",
    },
    {
        "name": "The Efficacious Portal Ward",
        "level": 4,
        "range": "0",
        "duration": "1 day/level",
        "aoe": '6" radius',
        "save": "None",
        "description": "All planar gates & portals sealed, teleportation and phase will not function in warded area.",
    },
    {
        "name": "The Engendering Weave",
        "level": 4,
        "range": "Touch",
        "duration": "1 hour/level",
        "aoe": "1 cubic foot/level",
        "save": "None",
        "description": "Create item of non-living matter - rope, door etc.",
    },
    {
        "name": "Evard's Black Tentacles",
        "level": 4,
        "range": '3"',
        "duration": "1 round/level",
        "aoe": "30 square feet/level",
        "save": "None",
        "description": "Writhing tentacles spring from ground. Number = caster level, 10' long, AC 4, HP = caster level, attack any creature in range. Save vs. spell or 2-8 damage and be held and squeezed for 3-12 automatic damage each round.",
    },
    {
        "name": "Felojun's Incendiary Rune",
        "level": 4,
        "range": "Touch",
        "duration": "Special",
        "aoe": "1 object",
        "save": "1/2",
        "description": 'Any creature other than caster + those attuned passing within 1/2" causes burst of flame 1" radius, 1d4 damage + 1 per caster level.',
    },
    {
        "name": "Flamsterd's Curtain of the Violet Conflagration",
        "level": 4,
        "range": '6"',
        "duration": "1 round/level",
        "aoe": "Special",
        "save": "None",
        "description": "Immobile curtain of fire 20' high, 20' long/level. 2-8 heat damage within 10' and 1-4 within 20' on one side of wall only. Passing through flames causes 2-12 damage + 1 per caster level. Undead take double damage.",
    },
    {
        "name": "The Gestation of the Ignoble Servitor",
        "level": 4,
        "range": '3"',
        "duration": "Permanent",
        "aoe": "Special",
        "save": "None",
        "description": "Creates a mephit from elemental matter (barrel of water, pile of slop etc). Alternatively roll on table:",
        "table": {
            "headers": ["D20", "Mephit type"],
            "rows": [
                ["1", "air"],
                ["2", "ash"],
                ["3", "dust"],
                ["4", "earth"],
                ["5", "fire"],
                ["6", "ice"],
                ["7", "lightning"],
                ["8", "magma"],
                ["9", "mineral"],
                ["10", "mist"],
                ["11", "ooze"],
                ["12", "radiance"],
                ["13", "salt"],
                ["14", "smoke"],
                ["15", "steam"],
                ["16", "water"],
                [
                    "17-20",
                    "Spell fails; pathetic half-formed elemental monstrosity lives 1d4 turns",
                ],
            ],
            "additional_text": "1 turn to complete. Mephit will not betray creator but check each day for desertion, loyalty 55% + charisma adjustment.",
        },
    },
    {
        "name": "Gilgad's Hallucinatory Locale",
        "level": 4,
        "range": '2"/level',
        "duration": "Special",
        "aoe": '1"x1" area/level',
        "save": "None",
        "description": "Illusion hides actual terrain - pond as grassy meadow, room as cobwebbed & dusty, etc. Lasts until contacted by intelligent creature.",
    },
    {
        "name": "Hlal's Umbral Monstrosity",
        "level": 4,
        "range": '3"',
        "duration": "1 round/level",
        "aoe": '2"x2"',
        "save": "Special",
        "description": "Create phantasms of monsters caster has seen - total HD equal to caster level. Monsters have 20% HP, fight normally. If targets disbelieve illusion then fight as AC 10 and 20% damage only.",
    },
    {
        "name": "The Illusion of Vile Arthropods",
        "level": 4,
        "range": '1"/level',
        "duration": "1 round/level",
        "aoe": '3"x3"',
        "save": "Negates",
        "description": "Targets covered by illusionary swarm of disgusting invertebrates. Save vs. spells each round or drop everything to compulsively brush off imaginary bugs.",
    },
    {
        "name": "The Impermanence of Being",
        "level": 4,
        "range": '3"',
        "duration": "1-6 turns",
        "aoe": "10' cube",
        "save": "None",
        "description": "Affected objects are 50% likely to vanish, checked independently for each viewer and with each viewing. Each viewer treats object as existing or not existing according to own perspective.",
    },
    {
        "name": "Johydee's Gentle Admonishment",
        "level": 4,
        "range": "0",
        "duration": "Instantaneous",
        "aoe": '1"x3" cone',
        "save": "Negates",
        "description": "Ear-splitting shout causes 2-12 damage and deafens for like number of round, cracks stone.",
    },
    {
        "name": "Leomund's Lamentable Belabourment",
        "level": 4,
        "range": '12"',
        "duration": "2 rounds + 1/level",
        "aoe": '6" x 6"',
        "save": "Negates",
        "description": "Save at -2 each round or confused. Confused creatures act randomly each round:",
        "table": {
            "headers": ["D10", "Action"],
            "rows": [
                ["1", "Wander away for 1 turn"],
                ["2-6", "Stand confused for 1 round"],
                ["7-8", "Attack nearest creature for 1 round"],
                ["9-0", "Attack magic-user and his or her party for 1 round"],
            ],
        },
    },
    {
        "name": "Lhegrand's Silvery Skin",
        "level": 4,
        "range": "Touch",
        "duration": "Special",
        "aoe": "1 creature",
        "save": "None",
        "description": "Total protection from 1 physical attack, then shatters.",
    },
    {
        "name": "The Minor Globe of Invulnerability",
        "level": 4,
        "range": "0",
        "duration": "1 round/level",
        "aoe": "Caster",
        "save": "None",
        "description": "Immunity to 3rd level spells and below. Spells can be cast out of globe normally.",
    },
    {
        "name": "Narissa's Blind Excess",
        "level": 4,
        "range": '1"/level',
        "duration": "Special",
        "aoe": '4"x4"',
        "save": "Negates",
        "description": "Cause blind emotional reaction, typical examples as follows. Rage: +1 to hit, +3 to damage, +5 temporary HP, fight berserk without regard for life. Fear: flee in panic 2d4 rounds. Happiness: +4 reaction rolls, won't attack unless greatly provoked. Hatred: -4 reaction rolls, tend towards violence. Lasts as long as caster concentrates.",
    },
    {
        "name": "The Onslaught of Dread Equines",
        "level": 4,
        "range": "0",
        "duration": "1 round/level",
        "aoe": '6" path 3" wide',
        "save": "Negates",
        "description": 'Save vs. spells at -2 or flee in panic, pursued by illusory sohmiens (nightmarish horse-beasts) for rounds equal to caster level. 10% chance summons d4 real sohmiens. Sohmien: AC 0, MV 24", HD 6+6, D 2d4/d6+4/d6+4, SA save vs. spell or flee in panic, XP 1800.',
    },
    {
        "name": "Otiluke's Resilient Sphere",
        "level": 4,
        "range": '2"',
        "duration": "1 round/level",
        "aoe": "1' diameter/level",
        "save": "Negates",
        "description": "Globe of force encases subject. Immune to damage, nothing can pass through either direction. Can be rolled.",
    },
    {
        "name": "Quaal's Flawless Duplicity",
        "level": 4,
        "range": "Touch",
        "duration": "1 hour/level",
        "aoe": "1 object",
        "save": "None",
        "description": "Create copy of any non-living item. Must fit within 20' cube.",
    },
    {
        "name": "Rary's Mnemonic Enhancer",
        "level": 4,
        "range": "0",
        "duration": "Instantaneous",
        "aoe": "Caster",
        "save": "None",
        "description": "Immediately regain formula of spell 3rd level or below cast in previous round.",
    },
    {
        "name": "The Seal Upon the Powers",
        "level": 4,
        "range": "Touch",
        "duration": "Permanent",
        "aoe": "Special",
        "save": "Special",
        "description": "Remove most permanent spells and baleful enchantments.",
    },
    {
        "name": "The Spell of Expansive Excavation",
        "level": 4,
        "range": '3"',
        "duration": "1 round/level",
        "aoe": "5' cube/round",
        "save": "None",
        "description": "Move earth (dirt, clay, loam, sand). Can create pits, ramparts, tunnels etc.",
    },
    {
        "name": "The Spell of Mercurial Anatomy",
        "level": 4,
        "range": "0",
        "duration": "2 turns/level",
        "aoe": "Caster",
        "save": "None",
        "description": "Change at will between form of any creature from as small as a wren to large as a hippo. Other abilities, hit points etc remain normal.",
    },
    {
        "name": "The Spell of the Peremptory Polymorph",
        "level": 4,
        "range": '1/2"/level',
        "duration": "Permanent",
        "aoe": "1 creature",
        "save": "Negates",
        "description": "Transform target into another creature. 100% chance assumes mentality of new form as well, -5% per point of Intelligence, checked daily.",
    },
    {
        "name": "The Spell of Wyrd",
        "level": 4,
        "range": '1/2"/level',
        "duration": "1 round/level",
        "aoe": "1 creature",
        "save": "Special",
        "description": "Imaginary doom visible only to target, strikes as 4 HD monster, invulnerable to attack & pass through any barrier. Successful hit means victim dies of fright. Disbelieve or knock out caster or target to destroy.",
    },
    {
        "name": "The Summons to the Inclement Clime",
        "level": 4,
        "range": '1"/level',
        "duration": "1 round",
        "aoe": "Special",
        "save": "None",
        "description": 'Either A) hailstones in 4" diameter inflict 3-30 damage, or B) sleet in 8" diameter blinds creatures 1 round, movement slowed 50% and 50% chance to slip and fall.',
    },
    {
        "name": "Tasha's Morbid Jest",
        "level": 4,
        "range": "0",
        "duration": "Special",
        "aoe": '3" diameter',
        "save": "Negates",
        "description": "Caster tells a joke. Save or stop to listen, and after punchline save again or incapacitated 1-10 rounds by painful laughter. The same joke will not work twice.",
    },
    {
        "name": "Tulrun's Filamentary Extension",
        "level": 4,
        "range": "0",
        "duration": "4 turns/level",
        "aoe": "Special",
        "save": "None",
        "description": 'Luminous filament shows recent path of creature visualised, within 1" radius of caster.',
    },
    {
        "name": "Alphon's Anguish of the North Wind",
        "level": 5,
        "range": "0",
        "duration": "Instantaneous",
        "aoe": 'Cone 1/2"/level',
        "save": "1/2",
        "description": "Freezing wind causes d4+1 damage per caster level, or save for half.",
    },
    {
        "name": "Archveult's Crude Fabrication",
        "level": 5,
        "range": '1/2"/level',
        "duration": "Permanent",
        "aoe": "1 cubic yard/level",
        "save": "None",
        "description": "Convert material into finished goods e.g. trees into wooden bridge, flax into clothes, etc.",
    },
    {
        "name": "The Augur of the Inscrutable Spheres",
        "level": 5,
        "range": "0",
        "duration": "Special",
        "aoe": "Special",
        "save": "None",
        "description": "Direct contact with minds from other planes, ask 1 question per 2 levels. Choose how distant a mind to contact:",
        "table": {
            "headers": [
                "Steps removed",
                "Chance of insanity",
                "Chance of knowledge",
                "Chance of veracity",
            ],
            "rows": [
                ["1", "20%", "60%", "65%"],
                ["2", "25%", "65%", "67%"],
                ["3", "30%", "70%", "70%"],
                ["4", "35%", "75%", "73%"],
                ["5", "40%", "80%", "75%"],
                ["6", "45%", "85%", "78%"],
                ["7", "50%", "90%", "81%"],
                ["8", "55%", "95%", "85%"],
                ["9 or more", "60%", "98%", "90%"],
            ],
            "additional_text": "Insanity strikes after 1st question asked, lasts 1 week per step removed. If insanity, then 1% chance per step of death.",
        },
    },
    {
        "name": "The Blade of Inexorable Disjection",
        "level": 5,
        "range": '1"',
        "duration": "1 round/level",
        "aoe": "0",
        "save": "None",
        "description": "Shimmering, sword-like plane of force mentally wielded as if fighter of 1/2 caster level (requires concentration). Causes 2-8 damage and severs extremities as Sword of Sharpness. Mutually destroys magic barriers.",
    },
    {
        "name": "Caligarde's Penetrating Vision",
        "level": 5,
        "range": "Touch",
        "duration": "1 round/level",
        "aoe": "1 cubic foot/level",
        "save": "None",
        "description": "Non-living matter becomes transparent.",
    },
    {
        "name": "The Charm of Untiring Nourishment",
        "level": 5,
        "range": "Touch",
        "duration": "12 hours/level",
        "aoe": "Special",
        "save": "None",
        "description": "Recipient encased in skin-tight bubble of comfortable air, does not hunger or thirst, can survive in any environment or plane. Duration divided by number affected.",
    },
    {
        "name": "Clambard's Remote Acquisition",
        "level": 5,
        "range": '1"/level',
        "duration": "2 rounds + 1/level",
        "aoe": "25 lb/level",
        "save": "None",
        "description": 'Move objects by concentrating on them - 2" first round, 4" second, 8" third etc, max 1024".',
    },
    {
        "name": "The Conjure of the Elemental Id",
        "level": 5,
        "range": '6"',
        "duration": "1 turn/level",
        "aoe": "Special",
        "save": "None",
        "description": "Conjure air, earth, fire or water elemental from suitable elemental matter (bonfire etc). Elementals are 16 HD. Unbroken concentration needed for control or will turn on caster and attack. 5% will turn on caster regardless, checked each round.",
    },
    {
        "name": "The Dweomer of Ignominious Dismissal",
        "level": 5,
        "range": '2"',
        "duration": "Instantaneous",
        "aoe": "1 creature",
        "save": "None",
        "description": "Force extraplanar being to return to plane of origin. Name and title must be given; normal magic resistance applies.",
    },
    {
        "name": "The Elocation of Ka",
        "level": 5,
        "range": '1"/level',
        "duration": "Special",
        "aoe": "1 creature",
        "save": "Special",
        "description": "Shift life force into special receptacle (gem or crystal). From there can sense presence and force exchange between receptacle and living target that fails saving throw, taking over target's body. Saving throw modified by difference in combined Intelligence and Wisdom between caster and target:",
        "table": {
            "headers": ["Difference", "Die adjustment"],
            "rows": [
                ["-9 or more", "+4"],
                ["-8 to -6", "+3"],
                ["-5 to -3", "+2"],
                ["-2 to 0", "+1"],
                ["1 to 4", "0"],
                ["5 to 8", "-1"],
                ["9 to 12", "-2"],
                ["13+", "-3"],
            ],
        },
    },
    {
        "name": "The Extirpation of the Ruinous Cloud",
        "level": 5,
        "range": '1"',
        "duration": "1 round/level",
        "aoe": '4"x2"x2" cloud',
        "save": "None",
        "description": 'Roiling fog kills instantly any creature 4 HD or below. 4+1 to 5+1 HD save vs. poison at -4 or die; 5+2 to 6 HD save normally. Cloud moves away from caster 1" per round, heavier than air.',
    },
    {
        "name": "Firdaan's Impenetrable Last Stand",
        "level": 5,
        "range": "Touch",
        "duration": "1 round/level",
        "aoe": "1 creature",
        "save": "None",
        "description": "Recipient surrounded by immobile shimmering sphere 5' diameter, totally protects against all non-magical weapons. Can use weapons normally from within sphere. Spells unaffected.",
    },
    {
        "name": "The Hebetation of the Intellect",
        "level": 5,
        "range": '1"/level',
        "duration": "Permanent",
        "aoe": "1 creature",
        "save": "Negates",
        "description": "Victim's brain reduced to childlike imbecility and insanity. Magic-users save at -4.",
    },
    {
        "name": "The Imperfect Invitation",
        "level": 5,
        "range": '1"',
        "duration": "Special",
        "aoe": "Special",
        "save": "Special",
        "description": "Summons extraplanar creature to be confined until it agrees to give service. Creature type must be stated, and name/title if any. In order to confine summoned creature, must prepare magic circle - takes 1 turn. 20% chance entrapped creature will break free and wreak vengeance, -1% per 1 turn and 1000 sp spent inscribing circle with special pigments etc. Any break in circle, even a straw, allows creature to break free.",
    },
    {
        "name": "Johydee's Indisputable Fantasy",
        "level": 5,
        "range": '6" + 1"/level',
        "duration": "1 round/level",
        "aoe": '2" square + 1"/level',
        "save": "Special",
        "description": "Illusion affecting all senses, operates according to program determined by caster. Believing creatures can suffer damage from illusionary effects.",
    },
    {
        "name": "Leomund's Dramatic Chest",
        "level": 5,
        "range": "Special",
        "duration": "60 days",
        "aoe": "2'x2'x3' chest",
        "save": "None",
        "description": "Store a chest on the ethereal plane, to be summoned with miniature replica. Chest must be 5000+ sp, hardwood & platinum, ivory & gold or bronze & silver. 1% cumulative chance/week chest will be discovered and tampered with, 5% chance draws through ethereal monster when summoned.",
    },
    {
        "name": "Mentor's Perfect Inertia",
        "level": 5,
        "range": '1"',
        "duration": "Permanent",
        "aoe": "3' cube",
        "save": "None",
        "description": "Natural repulsion between non-living object and living things (except caster). Creatures within 1' thrown back, or repulse object, depending on relative mass. Reverse causes powerful adherence.",
    },
    {
        "name": "The Oblong Barrier",
        "level": 5,
        "range": '3"',
        "duration": "1 turn + 1 rnd/level",
        "aoe": "10' square/level",
        "save": "None",
        "description": "Immobile, invisible, indestructible barrier prevents passage of anything in either direction, including all spells.",
    },
    {
        "name": "Pandelume's Paroxysm of Pain",
        "level": 5,
        "range": '3"',
        "duration": "1 round/level",
        "aoe": "1 creature",
        "save": "1/2",
        "description": "Convulsions, -2 AC and -4 to hit, 1d4 damage per round.",
    },
    {
        "name": "The Pattern of the Proscriptive Watchdog",
        "level": 5,
        "range": '1"',
        "duration": "1 hour/level",
        "aoe": "Special",
        "save": "None",
        "description": "Terrible phantasmal beast guards passage, door etc. Can detect invisible, astral etc creatures. Loud growling if any creature approaches, and strike as 10 HD for 3-18 damage. Cannot be combatted physically.",
    },
    {
        "name": "Phandaal's Semblance of Psyche",
        "level": 5,
        "range": '1"/level',
        "duration": "Special",
        "aoe": "Caster",
        "save": "None",
        "description": "Project immaterial duplicate of caster to any spot in range, can speak & cast spells through duplicate. Requires unbroken concentration.",
    },
    {
        "name": "The Reign of Long Nerves",
        "level": 5,
        "range": '1"/level',
        "duration": "Special",
        "aoe": "1 creature",
        "save": "Negates",
        "description": "Control target like an automaton. Immediate save at +2 if forced to take self-destructive action.",
        "table": {
            "headers": ["Intelligence", "Period Between Saving Throws"],
            "rows": [
                ["3 or less", "3 months"],
                ["4 to 6", "2 months"],
                ["7 to 9", "1 month"],
                ["10 to 12", "3 weeks"],
                ["13 to 14", "2 weeks"],
                ["15 to 16", "1 week"],
                ["17", "3 days"],
                ["18", "2 days"],
                ["19 or more", "1 day"],
            ],
        },
    },
    {
        "name": "The Satire of Life Renewed",
        "level": 5,
        "range": '1"',
        "duration": "Permanent",
        "aoe": "Special",
        "save": "None",
        "description": "Animate dead bodies. 1 skeleton or zombie per level, or equivalent in hit dice.",
    },
    {
        "name": "The Seven Hundred and Seventy Steps of Slumber",
        "level": 5,
        "range": "0",
        "duration": "Special",
        "aoe": "Caster",
        "save": "None",
        "description": "Fall asleep and enter the Dreamlands. May deliver a message to any sleeping creature personally known to the caster.",
    },
    {
        "name": "The Shroud of Agonising Immolation",
        "level": 5,
        "range": '3"',
        "duration": "1 round/level",
        "aoe": "1 creature",
        "save": "Negates",
        "description": "Target bursts into flames. 2-12 damage per round, plus 1-4 damage and ignites flammable objects in 10' radius. Saving throw each round.",
    },
    {
        "name": "Skye's Spell to Sidestep the Real",
        "level": 5,
        "range": '3"',
        "duration": "6 turns + 1/level",
        "aoe": "Special",
        "save": "None",
        "description": "Open passage through solid matter, 2' deep per level.",
    },
    {
        "name": "The Spell of Celeritous Relocalisation",
        "level": 5,
        "range": "Touch",
        "duration": "Instantaneous",
        "aoe": "Special",
        "save": "None",
        "description": "Transport caster and 250 lb + 150 lb per level, to anywhere on same plane.",
        "tables": [
            {
                "title": "Teleportation Results",
                "headers": [
                    "Destination is",
                    "High*",
                    "On target",
                    "Off target**",
                    "Mishap",
                    "Low***",
                ],
                "rows": [
                    ["Very familiar", "01", "02-98", "99", "00", "-"],
                    ["Studied carefully", "01-02", "03-95", "96-97", "98-99", "00"],
                    ["Seen casually", "01-04", "05-90", "91-94", "95-98", "99-00"],
                    ["Viewed once", "01-08", "09-80", "81-88", "89-96", "97-00"],
                    ["Never seen", "01-16", "17-60", "61-76", "77-92", "93-00"],
                ],
                "notes": [
                    "* 10' above ground per 1% missed.",
                    "** d100% distance travelled in random direction.",
                    "*** Instant death if area is solid.",
                ],
            },
            {
                "title": "Mishap",
                "headers": ["d20", "Mishap"],
                "rows": [
                    ["1", "High velocity arrival - hurled d100 feet in random direction"],
                    ["2", "Travellers scattered in 1 mile radius of arrival point"],
                    ["3", "Travellers separated - reroll arrival chances separately"],
                    ["4", "Only living matter transported"],
                    ["5", "Only non-living matter transported"],
                    ["6", "Out of phase - treat as Ethereal"],
                    ["7", "D100' radius surroundings transported along with travellers"],
                    ["8", "Transported d10 days back in time"],
                    ["9", "Transported d100 days forward in time"],
                    ["10", "Unexpected extradimensional passenger, roll random monster"],
                    ["11", "Spawn evil twins - vanish if killed"],
                    ["12", "Swap personalities - trade character sheets clockwise"],
                    ["13", "Materialise partially inside objects - d6 damage x HD"],
                    ["14", "Materialise missing pieces - save or lose an extremity"],
                    ["15", "Materialise upside down - d4 damage"],
                    ["16", "Swap places with something at point of arrival"],
                    ["17", "Explosion at target: 50', 6d6 damage, travellers unaffected"],
                    ["18", "Save vs. spells or turned inside-out"],
                    ["19", "Dumped into Astral Plane"],
                    ["20", "Travellers arrive safely, but are wearing different hats"],
                ],
            },
        ],
    },
    {
        "name": "Tenser's Destructive Resonance",
        "level": 5,
        "range": '6" + 1"/level',
        "duration": "Special",
        "aoe": "1 object",
        "save": "Special",
        "description": "Beam causes non-living objects to spontaneously explode. Larger objects more destructive but must hold beam for longer.",
        "table": {
            "headers": ["Weight (lb)", "Resonance time", "Base damage", "Explosive radius"],
            "rows": [
                ["1-5", "Instant", "1", "2'"],
                ["6-25", "Instant", "d4", "3'"],
                ["26-100", "1 round", "d6", "5'"],
                ["101-500", "2 rounds", "d8", "10'"],
                ["501-2000", "3 rounds", "d10", "15'"],
            ],
            "additional_text": "Explosion causes base damage x caster level (or save for half).",
        },
    },
    {
        "name": "Tzunk's Distance Distortion",
        "level": 5,
        "range": '1"/level',
        "duration": "1 turn/level",
        "aoe": '10" square/level',
        "save": "None",
        "description": "Distances halved, doubled, or anywhere in between in area of effect.",
    },
    {
        "name": "Yon's Obliging Parapet",
        "level": 5,
        "range": '1/2"/level',
        "duration": "Permanent",
        "aoe": "Special",
        "save": "None",
        "description": 'Wall of rock merges with existing stone. 100 square feet and 1/4" thick per caster level.',
    },
    {
        "name": "The Agency of Far Despatch",
        "level": 6,
        "range": "Touch",
        "duration": "Instantaneous",
        "aoe": "Special",
        "save": "None",
        "description": "Powerful forces hurl caster and 250 lb + 150 lb per level to any location on same plane, no error, or interplanar travel as below. 1 round to recover after transit.",
        "table": {
            "headers": [
                "Destination is",
                "On target",
                "1-10 miles",
                "1-100 miles",
                "1 plane",
                "2 planes",
                "Random plane",
            ],
            "rows": [
                ["Very familiar", "01-50", "51-90", "91-95", "96-97", "98-99", "00"],
                ["Studied carefully", "01-25", "26-50", "51-75", "76-83", "84-90", "91-00"],
                ["Seen casually", "01-10", "11-25", "26-50", "51-65", "66-80", "81-00"],
                ["Viewed once", "01-05", "06-10", "11-25", "26-48", "49-70", "71-00"],
                ["Never seen", "01", "04-05", "06-10", "11-35", "36-60", "61-00"],
            ],
        },
    },
    {
        "name": "Ao's Enervating Opalescent Eyes",
        "level": 6,
        "range": '2"',
        "duration": "1 round/3 levels",
        "aoe": "1 creature/round",
        "save": "Negates",
        "description": "Caster's gaze causes their choice of effect: Charm - target becomes totally loyal and docile to caster. Fear - refuse to face caster, cower or bolt (50/50) if confronted. Sicken - 1/2 ability scores, 1/2 movement, lose 1 Constitution per day until dead. Sleep - comatose slumber until wakened. Non-humanoid types save at +2.",
    },
    {
        "name": "The Avulsion of the Spirit-Soul",
        "level": 6,
        "range": "Touch",
        "duration": "Special",
        "aoe": "Special",
        "save": "None",
        "description": "Project soul onto Astral Plane. Affects caster plus up to 1 other creature per 2 levels.",
    },
    {
        "name": "The Binding of True Names",
        "level": 6,
        "range": '3"',
        "duration": "Special",
        "aoe": "1 creature",
        "save": "None",
        "description": "Speak true name of creature and cast spell. Must then chant desired effect in verse, preferably rhyme (takes 1 round). Command - subject obeys instruction. Imprison - subject magically transported/confined. Metamorphosis - subject transformed into something else. Minimus Containment - subject shrunk to 1 inch and imprisoned in gem or similar object. Slumber - subject sleeps, forever or until specified. Transport - subject transported to any location on any plane. Weakness - subject paralysed and unable to act.",
    },
    {
        "name": "The Call to the Assiduous Pursuer",
        "level": 6,
        "range": '1"',
        "duration": "Special",
        "aoe": "Special",
        "save": "None",
        "description": 'Invisible creature arrives in 1-4 turns and will obey spellcaster. Resents servitude and seeks to pervert instructions. The Assiduous Pursuer: AC 6, MV 6"/FL 24", HD 9, D 2-16/2-16, SD invisible, MR 30%, XP 2000. Faultless tracker. Flies silently and can carry 2 persons on back or draft horse in tentacles. If slain banished to own plane.',
    },
    {
        "name": "The Call to Inflexible Salvation",
        "level": 6,
        "range": '3"',
        "duration": "Special",
        "aoe": "Special",
        "save": "None",
        "description": "Summons powerful, specific demon, demigod, god etc, or their servant. Summoned creature is under no constraints. Spell ages caster 5 years due to cosmic strain.",
    },
    {
        "name": "The Contingency of the Foreknown",
        "level": 6,
        "range": "0",
        "duration": "1 day/level",
        "aoe": "Caster",
        "save": "None",
        "description": "Cast a spell; it will come into effect on caster's person when specified conditions are met.",
    },
    {
        "name": "Daern's Total Repulse",
        "level": 6,
        "range": "0",
        "duration": "1 round/2 levels",
        "aoe": '1" radius',
        "save": "None",
        "description": "Invisible, mobile field surrounds caster in 10' radius and repulses all creatures.",
    },
    {
        "name": "The Excellent Prismatic Spray",
        "level": 6,
        "range": '2"',
        "duration": "Instantaneous",
        "aoe": '1/2" square/level',
        "save": "None",
        "description": "Darts of prismatic fire instantly slay 2d20 hit dice of creatures. 8 HD or more get a saving throw.",
    },
    {
        "name": "Hornung's Indiscriminate Expulsion",
        "level": 6,
        "range": '3"',
        "duration": "Instantaneous",
        "aoe": "1 creature",
        "save": "Negates",
        "description": "Banish target to random plane.",
        "table": {
            "headers": ["d100", "Plane"],
            "rows": [
                ["01-04", "Abyss"],
                ["05-08", "Acheron"],
                ["09-12", "Arborea"],
                ["13-16", "Arcadia"],
                ["17-20", "Astral"],
                ["21-24", "Baator"],
                ["25-28", "Beastlands"],
                ["29-32", "Bytopia"],
                ["33-36", "Carceri"],
                ["37-40", "Elemental (Air, Earth, Fire, Water)"],
                ["41-44", "Elysium"],
                ["45-48", "Energy (Positive or Negative)"],
                ["49-52", "Ethereal"],
                ["53-56", "Gehenna"],
                ["57-60", "Grey Wastes"],
                ["61-64", "Limbo"],
                ["65-68", "Mechanus"],
                ["69-72", "Mount Olympus"],
                ["73-76", "Negative Quasi-Elemental (Vacuum, Ash, Dust, Salt)"],
                ["77-80", "Outlands"],
                ["81-84", "Pandemonium"],
                ["85-88", "Para-Elemental (Ice, Ooze, Magma, Smoke)"],
                ["89-92", "Positive Quasi-Elemental (Lightning, Mineral, Radiance, Steam)"],
                ["93-96", "Prime Material"],
                ["97-00", "Ysgard"],
            ],
        },
    },
    {
        "name": "The Infallible Retrotropic Field",
        "level": 6,
        "range": "0",
        "duration": "1 turn/level",
        "aoe": "1'/level diameter",
        "save": "None",
        "description": "Invisible field moves with caster, completely suppresses all magic in area of effect.",
    },
    {
        "name": "Khelpen's Permutation of Gravity",
        "level": 6,
        "range": '1/2"/level',
        "duration": "1 round/level",
        "aoe": '3"x3" square',
        "save": "None",
        "description": "Reverse gravity in area of effect.",
    },
    {
        "name": "The Labyrinth of Elongated Shadows",
        "level": 6,
        "range": '1"',
        "duration": "Special",
        "aoe": "1 creature",
        "save": "None",
        "description": "Target vanishes into mental labyrinth until they solve a maze provided by DM, or roll below.",
        "table": {
            "headers": ["Intelligence", "Time trapped"],
            "rows": [
                ["<3", "1d4 turns"],
                ["3-5", "5d4 rounds"],
                ["6-9", "4d4 rounds"],
                ["10-13", "3d4 rounds"],
                ["14-17", "2d4 rounds"],
                ["18+", "1d4 rounds"],
            ],
        },
    },
    {
        "name": "The Omnipotent Sphere",
        "level": 6,
        "range": "0",
        "duration": "1 round/2 levels",
        "aoe": "Caster",
        "save": "None",
        "description": "Impenetrable force protects caster absolutely from all physical damage.",
    },
    {
        "name": "Otiluke's Freezing Orb",
        "level": 6,
        "range": "Special",
        "duration": "1 round/level",
        "aoe": "Special",
        "save": "1/2",
        "description": "Globe of absolute zero freezes water (100 cubic feet/level) or can be thrown, shatters for 4-24 cold damage within 10' (save for half). Shatters if spell expires.",
    },
    {
        "name": "Otto's Irresistable Dance",
        "level": 6,
        "range": "Touch",
        "duration": "1-4 rounds",
        "aoe": "1 creature",
        "save": "None",
        "description": "Target spasmodically dances, -4 to attack and AC, can do nothing but shuffle and tap.",
    },
    {
        "name": "The Scrutiny of the Omniscient Eye",
        "level": 6,
        "range": "0",
        "duration": "1 round/level",
        "aoe": "Caster",
        "save": "Negates",
        "description": "Perceive all things as they actually are. First time casters save vs. magic or go insane. Reverse causes target to see things as they are not - rich is poor, rough is smooth, beautiful is ugly.",
    },
    {
        "name": "The Sequester to the Ethereal Coil",
        "level": 6,
        "range": "Touch",
        "duration": "1 hour/level",
        "aoe": "Special",
        "save": "Negates",
        "description": "Subject becomes Ethereal. Affects 1 creature per 2 levels, plus caster at his or her option.",
    },
    {
        "name": "Serten's Immaculate Simulacrum",
        "level": 6,
        "range": "Touch",
        "duration": "Permanent",
        "aoe": "1 creature",
        "save": "None",
        "description": "Create duplicate of creature from ice and snow. Requires token from original. Simulacrum has d20+40% of original's hit points, knowledge, levels etc. Obeys commands from caster.",
    },
    {
        "name": "The Seven Symbols of Solomon",
        "level": 6,
        "range": "Touch",
        "duration": "Special",
        "aoe": "Special",
        "save": "Negates",
        "description": "Magic rune affects creatures which see, touch or pass over it. Death - affects up to 80 hp of creatures. Discord - bicker and attack companions, lasts 2-8 rounds. Fear - flee 2d4 rounds, save at -2. Hopelessness - do nothing and submit to any demand, lasts 3-12 rounds. Insanity - go permanently insane. Pain - convulsions, -2 to AC and -4 to hit. Sleep - catatonic slumber for 1-12 turns.",
    },
    {
        "name": "Sirrian's Spell Engine",
        "level": 6,
        "range": '1"',
        "duration": "1 round/level",
        "aoe": '1" radius/level',
        "save": "None",
        "description": "Intangible wheel sucks up all spells cast in area of effect. Caster can cause wheel to fire random spell at target. Sucks up 2 spell levels per caster level; explodes if overloaded or touched by magic item for 6d4 damage 20' radius (save for half).",
    },
    {
        "name": "The Speculum of Retribution",
        "level": 6,
        "range": "0",
        "duration": "1 round/level",
        "aoe": "Special",
        "save": "Special",
        "description": "Reflects spells back towards caster if saving throw is made. Spells reflected back and forth until one side fails their saving throw.",
    },
    {
        "name": "The Spell of Elegant Dissolution",
        "level": 6,
        "range": '1/2"/level',
        "duration": "Permanent",
        "aoe": "1 object/creature",
        "save": "Negates",
        "description": 'Cause all matter to permanently vanish, up to 1" cubic volume. Affects magical matter (or energy) as well, including magical barriers. Living creatures and enchanted objects get a saving throw.',
    },
    {
        "name": "The Spell of Forlorn Encystment",
        "level": 6,
        "range": '3"',
        "duration": "Permanent",
        "aoe": "1 creature",
        "save": "Negates",
        "description": "Target rooted to the spot and begins to sink into the ground. If spell is completed, target is trapped forever in small sphere deep underground. Reverse frees trapped individual plus 1-100 others.",
    },
    {
        "name": "The Spell of Geas",
        "level": 6,
        "range": "Touch",
        "duration": "Special",
        "aoe": "1 creature",
        "save": "None",
        "description": "Willing individual magically commanded to carry out or refrain from some action; failure to comply causes target to sicken and die in 1 to 4 weeks.",
    },
    {
        "name": "The Spell of Temporal Disjunction",
        "level": 6,
        "range": "0",
        "duration": "Special",
        "aoe": "15' diameter",
        "save": "None",
        "description": "Stops time for 1 round for all but the caster.",
    },
    {
        "name": "The Spell of the Stone That Weeps in Silence",
        "level": 6,
        "range": '1"/level',
        "duration": "Permanent",
        "aoe": "1 creature",
        "save": "Negates",
        "description": "Turns target to stone along with all their possessions. Reverse frees petrified creatures.",
    },
    {
        "name": "Tenser's Transformation of the Heroic and Grotesque",
        "level": 6,
        "range": "0",
        "duration": "1 round/level",
        "aoe": "Caster",
        "save": "None",
        "description": "Caster's hit points double, +4 to AC, attacks as fighter of same level and +2 to damage. Goes berserk until spell ends.",
    },
    {
        "name": "The Tower of Indomitable Intellect",
        "level": 6,
        "range": '3"',
        "duration": "1 day",
        "aoe": "1 creature",
        "save": "None",
        "description": "Total protection from all mental attacks.",
    },
    {
        "name": "The Wrack of the Recalcitrant Spirit",
        "level": 6,
        "range": '1"',
        "duration": "Special",
        "aoe": "1 creature",
        "save": "None",
        "description": "Prepare a special document (4d8 hours and 5000 sp) bearing the name of a specific lower planar being. When read has following effects on being named: 1st round - being is immobilised unless magic resistance roll made, and 90% likely to retreat otherwise. 2nd round - acute pain and loss of 1 hit point per die. 3rd round - horrible pain, loss of 50% hp, and at end of round is confined to own plane in torture for number of years equal to caster level. Being is cumulative 25% likely per round to agree to any demand.",
    },
]


# Starting spells: magic-users begin knowing the Arcane Cypher plus
# three spells randomly determined (one from each list).
starting_spells = {
    "Offensive": [
        "The Charm of Appersonation",
        "Evard's Frictionless Field",
        "The Hypnotic Charm",
        "The Importunate Insult",
        "The Kaleidoscopic Spray",
        "Kazimir's Resplendent Couture",
        "Laeral's Baleful Aura",
        "The Metamorphoun of Fire",
        "Sirrian's Aggrandisement",
        "The Spell of Exquisite Repose",
    ],
    "Defensive": [
        "The Apotropaic Circle",
        "The Audible Glamer",
        "The Effervescent Lights of Kwalish",
        "The Expeditious Retreat",
        "The Heavenly Screen",
        "The Howling Rune",
        "The Imperturbable Quiescent Sphere",
        "Isain's Fortuitous Interruption",
        "The Lesser Sign of Sealing",
        "Otto's Arachnid Grip",
    ],
    "Miscellaneous": [
        "The Abstention of the Written Path",
        "The Call to the Familiar Spirit",
        "The Call to the Unseen Servant",
        "The Discerner of Enchantments",
        "The Indelible Emblem",
        "Melf's Impermeable Membrane",
        "Nahal's Reckless Dweomer",
        "Phandaal's Polyglottal Lobe",
        "The Spell of Pragmatic Amalgamation",
        "Tenser's Floating Disc",
    ],
}
